//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RequestTrackkingSystemEntities : DbContext
    {
        public RequestTrackkingSystemEntities()
            : base("name=RequestTrackkingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Kurum> tbl_Kurum { get; set; }
        public virtual DbSet<tbl_KurumIlgiliKisi> tbl_KurumIlgiliKisi { get; set; }
        public virtual DbSet<tbl_KurumsalTalep> tbl_KurumsalTalep { get; set; }
        public virtual DbSet<tbl_KurumsalTalepSurec> tbl_KurumsalTalepSurec { get; set; }
        public virtual DbSet<tbl_KurumsalTalepYetki> tbl_KurumsalTalepYetki { get; set; }
        public virtual DbSet<tbl_Dokuman> tbl_Dokuman { get; set; }
        public virtual DbSet<tbl_DosyaArsiv> tbl_DosyaArsiv { get; set; }
        public virtual DbSet<tbl_DosyaArsivSurec> tbl_DosyaArsivSurec { get; set; }
        public virtual DbSet<tbl_DosyaArsivYetki> tbl_DosyaArsivYetki { get; set; }
        public virtual DbSet<tbl_Durum> tbl_Durum { get; set; }
        public virtual DbSet<tbl_Duyuru> tbl_Duyuru { get; set; }
        public virtual DbSet<tbl_DuyuruYetki> tbl_DuyuruYetki { get; set; }
        public virtual DbSet<tbl_EgitimDurumu> tbl_EgitimDurumu { get; set; }
        public virtual DbSet<tbl_ErrorLog> tbl_ErrorLog { get; set; }
        public virtual DbSet<tbl_GelisYolu> tbl_GelisYolu { get; set; }
        public virtual DbSet<tbl_GorevKategori> tbl_GorevKategori { get; set; }
        public virtual DbSet<tbl_GorusOneri> tbl_GorusOneri { get; set; }
        public virtual DbSet<tbl_Grup> tbl_Grup { get; set; }
        public virtual DbSet<tbl_GrupOrtak> tbl_GrupOrtak { get; set; }
        public virtual DbSet<tbl_Hatirlatma> tbl_Hatirlatma { get; set; }
        public virtual DbSet<tbl_Il> tbl_Il { get; set; }
        public virtual DbSet<tbl_Ilce> tbl_Ilce { get; set; }
        public virtual DbSet<tbl_IlgiliKullanici> tbl_IlgiliKullanici { get; set; }
        public virtual DbSet<tbl_KapiGiris> tbl_KapiGiris { get; set; }
        public virtual DbSet<tbl_KapiGirisKisi> tbl_KapiGirisKisi { get; set; }
        public virtual DbSet<tbl_KapiGirisSurec> tbl_KapiGirisSurec { get; set; }
        public virtual DbSet<tbl_Kategori> tbl_Kategori { get; set; }
        public virtual DbSet<tbl_Kisi> tbl_Kisi { get; set; }
        public virtual DbSet<tbl_KisiGorev> tbl_KisiGorev { get; set; }
        public virtual DbSet<tbl_KisiMernis> tbl_KisiMernis { get; set; }
        public virtual DbSet<tbl_KisiSenkronizasyon> tbl_KisiSenkronizasyon { get; set; }
        public virtual DbSet<tbl_KisiTelefon> tbl_KisiTelefon { get; set; }
        public virtual DbSet<tbl_KulIlgiliKullanici> tbl_KulIlgiliKullanici { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_KullaniciAyar> tbl_KullaniciAyar { get; set; }
        public virtual DbSet<tbl_KullaniciLog> tbl_KullaniciLog { get; set; }
        public virtual DbSet<tbl_Mesajlasma> tbl_Mesajlasma { get; set; }
        public virtual DbSet<tbl_MesajlasmaLog> tbl_MesajlasmaLog { get; set; }
        public virtual DbSet<tbl_Not> tbl_Not { get; set; }
        public virtual DbSet<tbl_PrintMode> tbl_PrintMode { get; set; }
        public virtual DbSet<tbl_Rol> tbl_Rol { get; set; }
        public virtual DbSet<tbl_SikKullanilanlarMenu> tbl_SikKullanilanlarMenu { get; set; }
        public virtual DbSet<tbl_SistemSmsAyar> tbl_SistemSmsAyar { get; set; }
        public virtual DbSet<tbl_SistemSmsMailKisi> tbl_SistemSmsMailKisi { get; set; }
        public virtual DbSet<tbl_SMS> tbl_SMS { get; set; }
        public virtual DbSet<tbl_Tekrar> tbl_Tekrar { get; set; }
        public virtual DbSet<tbl_TempDokuman> tbl_TempDokuman { get; set; }
        public virtual DbSet<tbl_Sekreterya> tbl_Sekreterya { get; set; }
        public virtual DbSet<tbl_SekreteryaSurec> tbl_SekreteryaSurec { get; set; }
        public virtual DbSet<tbl_Talimat> tbl_Talimat { get; set; }
        public virtual DbSet<tbl_TalimatGorev> tbl_TalimatGorev { get; set; }
        public virtual DbSet<tbl_TalimatGorevSurec> tbl_TalimatGorevSurec { get; set; }
        public virtual DbSet<tbl_TalimatGorevYetki> tbl_TalimatGorevYetki { get; set; }
        public virtual DbSet<tbl_Talep> tbl_Talep { get; set; }
        public virtual DbSet<tbl_TalepKategori> tbl_TalepKategori { get; set; }
        public virtual DbSet<tbl_TalepReferans> tbl_TalepReferans { get; set; }
        public virtual DbSet<tbl_TalepSurec> tbl_TalepSurec { get; set; }
        public virtual DbSet<tbl_TalepYetki> tbl_TalepYetki { get; set; }
        public virtual DbSet<tbl_ProgramEntegre> tbl_ProgramEntegre { get; set; }
        public virtual DbSet<tbl_SiralamaGrup> tbl_SiralamaGrup { get; set; }
        public virtual DbSet<tbl_Ziyaret> tbl_Ziyaret { get; set; }
        public virtual DbSet<tbl_ZiyaretDurum> tbl_ZiyaretDurum { get; set; }
        public virtual DbSet<tbl_ZiyaretKisi> tbl_ZiyaretKisi { get; set; }
        public virtual DbSet<tbl_ZiyaretSurec> tbl_ZiyaretSurec { get; set; }
        public virtual DbSet<tbl_KisiSenkronizasyonBackup> tbl_KisiSenkronizasyonBackup { get; set; }
    }
}
