//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kategori()
        {
            this.tbl_TalepKategori = new HashSet<tbl_TalepKategori>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
        public int UstID { get; set; }
        public int TurID { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public string Renk { get; set; }
        public string YaziRenk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalepKategori> tbl_TalepKategori { get; set; }
    }
}
