//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZiyaretSurec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ZiyaretSurec()
        {
            this.tbl_Dokuman = new HashSet<tbl_Dokuman>();
        }
    
        public int ID { get; set; }
        public int ZiyaretID { get; set; }
        public string Aciklama { get; set; }
        public int TurID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int IslemKulID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dokuman> tbl_Dokuman { get; set; }
        public virtual tbl_Ziyaret tbl_Ziyaret { get; set; }
    }
}
