//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mesajlasma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Mesajlasma()
        {
            this.tbl_MesajlasmaLog = new HashSet<tbl_MesajlasmaLog>();
        }
    
        public int ID { get; set; }
        public string Mesaj { get; set; }
        public int GonderenKullaniciID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public Nullable<int> AlanKullaniciID { get; set; }
        public Nullable<int> AlanGrupID { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MesajlasmaLog> tbl_MesajlasmaLog { get; set; }
    }
}
