//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KisiMernis
    {
        public long TCK { get; set; }
        public string AdSoyad { get; set; }
        public int Cinsiyet { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public int MedeniHal { get; set; }
        public int NufusIlID { get; set; }
        public int NufusIlceID { get; set; }
        public string DogumYeri { get; set; }
        public string AnaAdi { get; set; }
        public string BabaAdi { get; set; }
        public System.DateTime SonSorguTarihi { get; set; }
        public int SorgulanmaSayisi { get; set; }
        public int SonIslemKullaniciID { get; set; }
    }
}
