//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kisi()
        {
            this.tbl_KurumIlgiliKisi = new HashSet<tbl_KurumIlgiliKisi>();
            this.tbl_Dokuman = new HashSet<tbl_Dokuman>();
            this.tbl_KapiGirisKisi = new HashSet<tbl_KapiGirisKisi>();
            this.tbl_KisiGorev = new HashSet<tbl_KisiGorev>();
            this.tbl_Not = new HashSet<tbl_Not>();
            this.tbl_KisiTelefon = new HashSet<tbl_KisiTelefon>();
            this.tbl_Kullanici = new HashSet<tbl_Kullanici>();
            this.tbl_Sekreterya = new HashSet<tbl_Sekreterya>();
            this.tbl_SistemSmsMailKisi = new HashSet<tbl_SistemSmsMailKisi>();
            this.tbl_SMS = new HashSet<tbl_SMS>();
            this.tbl_Talep = new HashSet<tbl_Talep>();
            this.tbl_TalepReferans = new HashSet<tbl_TalepReferans>();
            this.tbl_ZiyaretKisi = new HashSet<tbl_ZiyaretKisi>();
        }
    
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string TCK { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> Cinsiyet { get; set; }
        public Nullable<int> MedeniDurum { get; set; }
        public Nullable<int> IslemKulID { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public string SicilNo { get; set; }
        public string EPosta { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> EgitimDurumu { get; set; }
        public string GorevTanimi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KurumIlgiliKisi> tbl_KurumIlgiliKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dokuman> tbl_Dokuman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KapiGirisKisi> tbl_KapiGirisKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KisiGorev> tbl_KisiGorev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Not> tbl_Not { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KisiTelefon> tbl_KisiTelefon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Kullanici> tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sekreterya> tbl_Sekreterya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SistemSmsMailKisi> tbl_SistemSmsMailKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SMS> tbl_SMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Talep> tbl_Talep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalepReferans> tbl_TalepReferans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretKisi> tbl_ZiyaretKisi { get; set; }
    }
}
