//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DosyaArsivSurec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DosyaArsivSurec()
        {
            this.tbl_DosyaArsivYetki = new HashSet<tbl_DosyaArsivYetki>();
        }
    
        public int ID { get; set; }
        public int DosyaArsivID { get; set; }
        public string Aciklama { get; set; }
        public int IslemKulID { get; set; }
        public int SurecTurID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        public virtual tbl_DosyaArsiv tbl_DosyaArsiv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DosyaArsivYetki> tbl_DosyaArsivYetki { get; set; }
    }
}
