//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tekrar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Tekrar()
        {
            this.tbl_Hatirlatma = new HashSet<tbl_Hatirlatma>();
            this.tbl_Ziyaret = new HashSet<tbl_Ziyaret>();
        }
    
        public int ID { get; set; }
        public int ZamanTurID { get; set; }
        public int Sefer { get; set; }
        public int Sayi { get; set; }
        public string Gun { get; set; }
        public Nullable<System.DateTime> SonTarihi { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Hatirlatma> tbl_Hatirlatma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ziyaret> tbl_Ziyaret { get; set; }
    }
}
