//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KurumIlgiliKisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KurumIlgiliKisi()
        {
            this.tbl_KurumsalTalep = new HashSet<tbl_KurumsalTalep>();
        }
    
        public int ID { get; set; }
        public int KisiID { get; set; }
        public int KurumID { get; set; }
        public Nullable<int> IlID { get; set; }
        public Nullable<int> IlceID { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        public virtual tbl_Kurum tbl_Kurum { get; set; }
        public virtual tbl_Kisi tbl_Kisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KurumsalTalep> tbl_KurumsalTalep { get; set; }
    }
}
