//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GorevKategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_GorevKategori()
        {
            this.tbl_KisiGorev = new HashSet<tbl_KisiGorev>();
            this.tbl_KisiGorev1 = new HashSet<tbl_KisiGorev>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
        public int UstID { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<int> SecimTur { get; set; }
        public Nullable<int> Limit { get; set; }
        public Nullable<int> Puan { get; set; }
        public string GorunenIsim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KisiGorev> tbl_KisiGorev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KisiGorev> tbl_KisiGorev1 { get; set; }
    }
}
