//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZiyaretKisi
    {
        public int ZiyaretID { get; set; }
        public int KisiID { get; set; }
        public Nullable<bool> isTemsilci { get; set; }
        public string ZiyaretKisiNot { get; set; }
        public bool isReferans { get; set; }
        public Nullable<bool> isGeldi { get; set; }
        public Nullable<System.DateTime> GelisTarihi { get; set; }
    
        public virtual tbl_Kisi tbl_Kisi { get; set; }
        public virtual tbl_Ziyaret tbl_Ziyaret { get; set; }
    }
}
