//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GorusOneri
    {
        public int ID { get; set; }
        public string Mesaj { get; set; }
        public int KulID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int IlgiliMesajID { get; set; }
        public bool isOkundu { get; set; }
        public string Baslik { get; set; }
        public string DokumanAdi { get; set; }
        public string Dosya { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
    }
}
