//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KurumsalTalep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KurumsalTalep()
        {
            this.tbl_KurumsalTalepYetki = new HashSet<tbl_KurumsalTalepYetki>();
            this.tbl_KurumsalTalepSurec = new HashSet<tbl_KurumsalTalepSurec>();
        }
    
        public int ID { get; set; }
        public int KurumID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> IlID { get; set; }
        public Nullable<int> IlceID { get; set; }
        public int KategoriID { get; set; }
        public Nullable<int> IlgiliKisiID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int OncelikID { get; set; }
        public int DurumID { get; set; }
        public int IslemKulID { get; set; }
        public Nullable<int> GrupID { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> HatirlatmaTarihi { get; set; }
    
        public virtual tbl_Kurum tbl_Kurum { get; set; }
        public virtual tbl_KurumIlgiliKisi tbl_KurumIlgiliKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KurumsalTalepYetki> tbl_KurumsalTalepYetki { get; set; }
        public virtual tbl_Grup tbl_Grup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KurumsalTalepSurec> tbl_KurumsalTalepSurec { get; set; }
    }
}
