//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TalepKategori
    {
        public int ID { get; set; }
        public int TalepID { get; set; }
        public int KategoriID { get; set; }
    
        public virtual tbl_Kategori tbl_Kategori { get; set; }
        public virtual tbl_Talep tbl_Talep { get; set; }
    }
}
