//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TalepReferans
    {
        public int TalepID { get; set; }
        public int KisiID { get; set; }
        public string ReferansNot { get; set; }
    
        public virtual tbl_Kisi tbl_Kisi { get; set; }
        public virtual tbl_Talep tbl_Talep { get; set; }
    }
}
