//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Grup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Grup()
        {
            this.tbl_KurumsalTalep = new HashSet<tbl_KurumsalTalep>();
            this.tbl_KurumsalTalepYetki = new HashSet<tbl_KurumsalTalepYetki>();
            this.tbl_GrupOrtak = new HashSet<tbl_GrupOrtak>();
            this.tbl_IlgiliKullanici = new HashSet<tbl_IlgiliKullanici>();
            this.tbl_Kullanici = new HashSet<tbl_Kullanici>();
            this.tbl_Not = new HashSet<tbl_Not>();
            this.tbl_Sekreterya = new HashSet<tbl_Sekreterya>();
            this.tbl_Talep = new HashSet<tbl_Talep>();
            this.tbl_TalepYetki = new HashSet<tbl_TalepYetki>();
            this.tbl_Ziyaret = new HashSet<tbl_Ziyaret>();
            this.tbl_Rol = new HashSet<tbl_Rol>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int UstID { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public string YetkiNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KurumsalTalep> tbl_KurumsalTalep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KurumsalTalepYetki> tbl_KurumsalTalepYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GrupOrtak> tbl_GrupOrtak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_IlgiliKullanici> tbl_IlgiliKullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Kullanici> tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Not> tbl_Not { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sekreterya> tbl_Sekreterya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Talep> tbl_Talep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalepYetki> tbl_TalepYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ziyaret> tbl_Ziyaret { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Rol> tbl_Rol { get; set; }
    }
}
