//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KapiGirisKisi
    {
        public int ID { get; set; }
        public int KapiGirisID { get; set; }
        public int KisiID { get; set; }
        public string KisiNot { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public bool isGeldi { get; set; }
    
        public virtual tbl_KapiGiris tbl_KapiGiris { get; set; }
        public virtual tbl_Kisi tbl_Kisi { get; set; }
    }
}
