//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KisiTelefon
    {
        public int ID { get; set; }
        public int KisiID { get; set; }
        public string Numara { get; set; }
        public bool isVarsayilan { get; set; }
        public Nullable<bool> isMobile { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> isYurtDisi { get; set; }
    
        public virtual tbl_Kisi tbl_Kisi { get; set; }
    }
}
