//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kurum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kurum()
        {
            this.tbl_KurumIlgiliKisi = new HashSet<tbl_KurumIlgiliKisi>();
            this.tbl_KurumsalTalep = new HashSet<tbl_KurumsalTalep>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Adres { get; set; }
        public string Aciklama { get; set; }
        public int SecimTur { get; set; }
        public int UstID { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KurumIlgiliKisi> tbl_KurumIlgiliKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KurumsalTalep> tbl_KurumsalTalep { get; set; }
    }
}
