//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TalepYetki
    {
        public int ID { get; set; }
        public int TalepID { get; set; }
        public Nullable<int> GrupID { get; set; }
        public int YetkiTurID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int EkleyenKullaniciID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> SurecID { get; set; }
        public Nullable<bool> isAktif { get; set; }
    
        public virtual tbl_Grup tbl_Grup { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        public virtual tbl_Talep tbl_Talep { get; set; }
    }
}
