//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KisiSenkronizasyon
    {
        public int ID { get; set; }
        public string TCK { get; set; }
        public string Adsoyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> Cinsiyet { get; set; }
        public Nullable<int> MedeniDurum { get; set; }
        public string SicilNo { get; set; }
        public string Eposta { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> EgitimDurumu { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon1Aciklama { get; set; }
        public string Telefon2 { get; set; }
        public string Telefon2Aciklama { get; set; }
        public string Telefon3 { get; set; }
        public string Telefon3Aciklama { get; set; }
        public string Telefon4 { get; set; }
        public string Telefon4Aciklama { get; set; }
        public Nullable<int> GorevKategoriID { get; set; }
        public Nullable<int> GorevIl { get; set; }
        public Nullable<int> GorevIlce { get; set; }
        public string GorevAciklama { get; set; }
    }
}
