//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hatirlatma
    {
        public int ID { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime Tarih { get; set; }
        public int IslemKulID { get; set; }
        public int GrupID { get; set; }
        public Nullable<int> TekrarID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        public virtual tbl_Tekrar tbl_Tekrar { get; set; }
    }
}
