//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sekreterya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Sekreterya()
        {
            this.tbl_SekreteryaSurec = new HashSet<tbl_SekreteryaSurec>();
        }
    
        public int ID { get; set; }
        public int TurID { get; set; }
        public Nullable<int> KisiID { get; set; }
        public Nullable<int> ArananKulID { get; set; }
        public int KategoriID { get; set; }
        public Nullable<int> DurumID { get; set; }
        public string Aciklama { get; set; }
        public int IslemKulID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int GrupID { get; set; }
        public Nullable<int> GelisYoluID { get; set; }
        public string KisiNot { get; set; }
        public Nullable<bool> isGonderildi { get; set; }
    
        public virtual tbl_Grup tbl_Grup { get; set; }
        public virtual tbl_Kisi tbl_Kisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SekreteryaSurec> tbl_SekreteryaSurec { get; set; }
    }
}
