//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Talimat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Talimat()
        {
            this.tbl_TalimatGorev = new HashSet<tbl_TalimatGorev>();
        }
    
        public int ID { get; set; }
        public string Baslik { get; set; }
        public int IslemKulID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int GrupID { get; set; }
        public bool isGenel { get; set; }
        public Nullable<int> ZiyaretID { get; set; }
    
        public virtual tbl_Ziyaret tbl_Ziyaret { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalimatGorev> tbl_TalimatGorev { get; set; }
    }
}
