//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DosyaArsivYetki
    {
        public int ID { get; set; }
        public int DosyaArsivID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> GrupID { get; set; }
        public bool isAktif { get; set; }
        public int DosyaArsivSurecID { get; set; }
        public int IslemKulID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        public virtual tbl_DosyaArsiv tbl_DosyaArsiv { get; set; }
        public virtual tbl_DosyaArsivSurec tbl_DosyaArsivSurec { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
    }
}
