//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KapiGiris
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KapiGiris()
        {
            this.tbl_KapiGirisKisi = new HashSet<tbl_KapiGirisKisi>();
            this.tbl_KapiGirisSurec = new HashSet<tbl_KapiGirisSurec>();
        }
    
        public int ID { get; set; }
        public string GelenNot { get; set; }
        public int IlgiliKullaniciID { get; set; }
        public int IslemKulID { get; set; }
        public int DurumID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KapiGirisKisi> tbl_KapiGirisKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KapiGirisSurec> tbl_KapiGirisSurec { get; set; }
    }
}
