//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DuyuruYetki
    {
        public int ID { get; set; }
        public int DuyuruID { get; set; }
        public int GrupID { get; set; }
    
        public virtual tbl_Duyuru tbl_Duyuru { get; set; }
    }
}
