//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TalimatGorevYetki
    {
        public int ID { get; set; }
        public int TalimatGorevID { get; set; }
        public Nullable<int> IlgiliKulID { get; set; }
        public Nullable<int> IlgiliGrupID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int IslemKulID { get; set; }
        public bool isAktif { get; set; }
        public int TalimatGorevSurecID { get; set; }
    
        public virtual tbl_TalimatGorev tbl_TalimatGorev { get; set; }
        public virtual tbl_TalimatGorevSurec tbl_TalimatGorevSurec { get; set; }
    }
}
