//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TalimatGorev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TalimatGorev()
        {
            this.tbl_Dokuman = new HashSet<tbl_Dokuman>();
            this.tbl_TalimatGorevSurec = new HashSet<tbl_TalimatGorevSurec>();
            this.tbl_TalimatGorevYetki = new HashSet<tbl_TalimatGorevYetki>();
        }
    
        public int ID { get; set; }
        public int TalimatID { get; set; }
        public string Aciklama { get; set; }
        public string Baslik { get; set; }
        public int DurumID { get; set; }
        public Nullable<System.DateTime> SonTarih { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int IslemKulID { get; set; }
        public Nullable<int> IlgiliGorevID { get; set; }
        public Nullable<int> ProgramTarihiTotal { get; set; }
        public Nullable<int> IlgiliProgramID { get; set; }
        public Nullable<int> KopyaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dokuman> tbl_Dokuman { get; set; }
        public virtual tbl_Talimat tbl_Talimat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalimatGorevSurec> tbl_TalimatGorevSurec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalimatGorevYetki> tbl_TalimatGorevYetki { get; set; }
    }
}
