//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PrintMode
    {
        public int ID { get; set; }
        public Nullable<int> Genislik { get; set; }
        public Nullable<int> Yukseklik { get; set; }
        public string Ad { get; set; }
        public byte[] Resim { get; set; }
        public Nullable<int> PaddingTop { get; set; }
        public Nullable<int> PaddingRight { get; set; }
        public Nullable<int> PaddingBottom { get; set; }
        public Nullable<int> PaddingLeft { get; set; }
        public string Header { get; set; }
    }
}
