//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMS
    {
        public int ID { get; set; }
        public int KayitID { get; set; }
        public int KisiID { get; set; }
        public string Mesaj { get; set; }
        public int TurID { get; set; }
        public Nullable<bool> isGonderildi { get; set; }
        public Nullable<System.DateTime> GonderilmeTarihi { get; set; }
        public int IslemKulID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public string DurumBilgisi { get; set; }
        public int DenemeSayisi { get; set; }
        public Nullable<int> MesajTakipID { get; set; }
    
        public virtual tbl_Kisi tbl_Kisi { get; set; }
    }
}
