//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Dokuman
    {
        public int ID { get; set; }
        public Nullable<int> IlgiliID { get; set; }
        public int TurID { get; set; }
        public string DokumanAdi { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int IslemKulID { get; set; }
        public string Aciklama { get; set; }
        public string Boyut { get; set; }
        public string Uzanti { get; set; }
        public string Dosya { get; set; }
        public Nullable<int> TalepID { get; set; }
        public Nullable<int> TalepSurecID { get; set; }
        public Nullable<int> ZiyaretID { get; set; }
        public Nullable<int> ZiyaretSurecID { get; set; }
        public Nullable<int> TalimatGorevID { get; set; }
        public Nullable<int> KisiID { get; set; }
        public Nullable<int> DosyaArsivID { get; set; }
    
        public virtual tbl_DosyaArsiv tbl_DosyaArsiv { get; set; }
        public virtual tbl_Kisi tbl_Kisi { get; set; }
        public virtual tbl_Talep tbl_Talep { get; set; }
        public virtual tbl_TalepSurec tbl_TalepSurec { get; set; }
        public virtual tbl_TalimatGorev tbl_TalimatGorev { get; set; }
        public virtual tbl_Ziyaret tbl_Ziyaret { get; set; }
        public virtual tbl_ZiyaretSurec tbl_ZiyaretSurec { get; set; }
    }
}
