//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kullanici()
        {
            this.tbl_KurumsalTalepYetki = new HashSet<tbl_KurumsalTalepYetki>();
            this.tbl_DosyaArsivYetki = new HashSet<tbl_DosyaArsivYetki>();
            this.tbl_GorusOneri = new HashSet<tbl_GorusOneri>();
            this.tbl_KulIlgiliKullanici = new HashSet<tbl_KulIlgiliKullanici>();
            this.tbl_KullaniciAyar = new HashSet<tbl_KullaniciAyar>();
            this.tbl_KullaniciLog = new HashSet<tbl_KullaniciLog>();
            this.tbl_Mesajlasma = new HashSet<tbl_Mesajlasma>();
            this.tbl_SikKullanilanlarMenu = new HashSet<tbl_SikKullanilanlarMenu>();
            this.tbl_TalepYetki = new HashSet<tbl_TalepYetki>();
            this.tbl_Ziyaret = new HashSet<tbl_Ziyaret>();
            this.tbl_Rol = new HashSet<tbl_Rol>();
        }
    
        public int ID { get; set; }
        public int KisiID { get; set; }
        public string Sifre { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public bool isAktif { get; set; }
        public Nullable<int> GrupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KurumsalTalepYetki> tbl_KurumsalTalepYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DosyaArsivYetki> tbl_DosyaArsivYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GorusOneri> tbl_GorusOneri { get; set; }
        public virtual tbl_Grup tbl_Grup { get; set; }
        public virtual tbl_Kisi tbl_Kisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KulIlgiliKullanici> tbl_KulIlgiliKullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KullaniciAyar> tbl_KullaniciAyar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KullaniciLog> tbl_KullaniciLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Mesajlasma> tbl_Mesajlasma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SikKullanilanlarMenu> tbl_SikKullanilanlarMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalepYetki> tbl_TalepYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ziyaret> tbl_Ziyaret { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Rol> tbl_Rol { get; set; }
    }
}
