//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Talep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Talep()
        {
            this.tbl_Dokuman = new HashSet<tbl_Dokuman>();
            this.tbl_TalepSurec = new HashSet<tbl_TalepSurec>();
            this.tbl_TalepKategori = new HashSet<tbl_TalepKategori>();
            this.tbl_TalepReferans = new HashSet<tbl_TalepReferans>();
            this.tbl_TalepYetki = new HashSet<tbl_TalepYetki>();
            this.tbl_Ziyaret = new HashSet<tbl_Ziyaret>();
        }
    
        public int ID { get; set; }
        public int KisiID { get; set; }
        public string Aciklama { get; set; }
        public int IlID { get; set; }
        public Nullable<int> IlceID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int DurumID { get; set; }
        public int OncelikID { get; set; }
        public Nullable<int> IlgiliKurumID { get; set; }
        public int IslemKulID { get; set; }
        public Nullable<int> GrupID { get; set; }
        public Nullable<System.DateTime> HatirlatmaTarihi { get; set; }
        public bool isDeleted { get; set; }
        public int GelisYoluID { get; set; }
        public Nullable<int> IletenKulID { get; set; }
        public Nullable<System.DateTime> GelisTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dokuman> tbl_Dokuman { get; set; }
        public virtual tbl_Grup tbl_Grup { get; set; }
        public virtual tbl_Kisi tbl_Kisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalepSurec> tbl_TalepSurec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalepKategori> tbl_TalepKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalepReferans> tbl_TalepReferans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TalepYetki> tbl_TalepYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ziyaret> tbl_Ziyaret { get; set; }
    }
}
