//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SistemSmsAyar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SistemSmsAyar()
        {
            this.tbl_SistemSmsMailKisi = new HashSet<tbl_SistemSmsMailKisi>();
        }
    
        public int ID { get; set; }
        public string Turu { get; set; }
        public int SecimTurID { get; set; }
        public string Icerik { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public bool isAktif { get; set; }
        public int IslemKulID { get; set; }
        public bool isBirlikte { get; set; }
        public string TelefonDeger { get; set; }
        public string MailDeger { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SistemSmsMailKisi> tbl_SistemSmsMailKisi { get; set; }
    }
}
